DROP TABLE dish IF EXISTS;
DROP TABLE user IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS BIGINT START WITH 1;

CREATE TABLE restaurant
(
    id            BIGINT       GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name          VARCHAR(60)  NOT NULL,
    votes_count   INTEGER      NOT NULL
);

CREATE TABLE user
(
    id                        BIGINT        GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name                      VARCHAR(60)   NOT NULL,
    email                     VARCHAR(255)  NOT NULL,
    password                  VARCHAR(60)   NOT NULL,
    role                      VARCHAR(5)    NOT NULL,
    chosen_restaurant_id      BIGINT        REFERENCES restaurant(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON user (email);

CREATE TABLE dish (
    id                BIGINT      GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name              VARCHAR(60) NOT NULL,
    price             DOUBLE      NOT NULL,
    restaurant_id     BIGINT      NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

INSERT INTO user (name, email, password, role, chosen_restaurant_id)
VALUES ('User1', 'user1@gmail.com', '$2y$12$4Ze4dPxvc/iltIpMKNhY1OtuKoq1ZhIkE6oPL273tfauKImiDtShu', 'USER', null),
       ('User2', 'user2@gmail.com', '$2y$12$Z5qVocXKClVIQDvL08s7ROu4IEvcOdZM5h2hERXsfp7tqV71lhsje', 'USER', null),
       ('Admin1', 'admin1@gmail.com', '$2y$12$Y0xiSfiPOkEdz5gRWDdMPOr.69ouTbjFy/BkiM.U4yW5FZ6txgsOK', 'ADMIN', null);

INSERT INTO restaurant(name, votes_count)
VALUES ('Some restaurant', 0),
       ('Another restaurant', 0);

INSERT INTO dish(name, price, restaurant_id)
VALUES ('Fish', 23.4, 4),
       ('Steak', 45.5, 4),
       ('Salad', 12.4, 5),
       ('Soup', 20.5, 5);

